name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
          architecture: 'x64'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
